// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBeIJ_JIVdCdeJjgYvAJb4xMsh9SeZSpI',
    appId: '1:94293805920:web:51c1d019b1ce2d8ab9ec05',
    messagingSenderId: '94293805920',
    projectId: 'eplatform-812ae',
    authDomain: 'eplatform-812ae.firebaseapp.com',
    databaseURL: 'https://eplatform-812ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eplatform-812ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOsncsG-sdPI5zHGOVyojEzeLK4ZFlGuk',
    appId: '1:94293805920:android:d6a1dfa075a23dcdb9ec05',
    messagingSenderId: '94293805920',
    projectId: 'eplatform-812ae',
    databaseURL: 'https://eplatform-812ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eplatform-812ae.appspot.com',
  );
}
